export default {
    card_name: { required: true, message: '请输入卡片完整名称', trigger: 'blur' },
    cn_category: { required: true, message: '请输入卡类别名称(中文)', trigger: 'blur' },
	eng_category: { required: true, message: '请输入卡片类别名称(英文)', trigger: 'blur' },
	particular_year: { required: true, message: '请选择卡片年份', trigger: 'blur' },
	cn_publisher: { required: true, message: '请输入发行商名称(中文)', trigger: 'blur' },
	eng_publisher: { required: true, message: '请输入发行商名称(英文)', trigger: 'blur' },
	abbr_ranks: { required: true, message: '请输入队伍中文简称', trigger: 'blur' },
	cn_ranks: { required: true, message: '请输入队伍名称(中文)', trigger: 'blur' },
	eng_ranks: { required: true, message: '请输入队伍名称(英文)', trigger: 'blur' },
	card_series: { required: true, message: '请输入系列', trigger: 'blur' },
	abbr_series: { required: true, message: '请输入系列(昵称)', trigger: 'blur' },
	cn_sub_series: { required: true, message: '请输入子系列', trigger: 'blur' },
	eng_sub_series: { required: true, message: '请输入子系列(昵称)', trigger: 'blur' },
	card_number: { required: true, message: '请输入卡片编号', trigger: 'blur' },
	cn_role: { required: true, message: '请输入角色名称(中文)', trigger: 'blur' },
	eng_role: { required: true, message: '请输入角色名称(英文)', trigger: 'blur' },
	cn_position: { required: true, message: '请输入位置名称(中文)', trigger: 'blur' },
	eng_position: { required: true, message: '请输入位置名称(英文)', trigger: 'blur' },
	card_cover: { required: true, message: '请选择卡片封面图', trigger: 'change' },
	card_img: { required: true, message: '请选择卡片背面图', trigger: 'change' },
	img_publisher: { required: true, message: '请选择发行商logo', trigger: 'change' },
	img_ranks: { required: true, message: '请选择队伍logo', trigger: 'change' },
	img_role: { required: true, message: '请选择角色logo', trigger: 'change' },
}