export default {
    card_name: { required: true, message: '请输入卡片完整名称', trigger: 'blur' },
    cn_category: { required: true, message: '请输入种类(中文)', trigger: 'blur' },
	eng_category: { required: true, message: '请输入种类(英文)', trigger: 'blur' },
	card_category: { required: true, message: '请输入种类(昵称)', trigger: 'blur' },
	particular_year: { required: true, message: '请选择卡片年份', trigger: 'blur' },
	cn_publisher: { required: true, message: '请输入发行商名称(中文)', trigger: 'blur' },
	eng_publisher: { required: true, message: '请输入发行商名称(英文)', trigger: 'blur' },
	abbr_ranks: { required: true, message: '请输入卡牌分类', trigger: 'blur' },
	cn_attribute: { required: true, message: '请输入属性(中文)', trigger: 'blur' },
	eng_attribute: { required: true, message: '请输入属性(英文)', trigger: 'blur' },
	cn_language: { required: true, message: '请输入语言(中文)', trigger: 'blur' },
	eng_language: { required: true, message: '请输入语言(英文)', trigger: 'blur' },
	cn_series_types: { required: true, message: '请输入系列种类(中文)', trigger: 'blur' },
	eng_series_types: { required: true, message: '请输入系列种类(英文)', trigger: 'blur' },
	card_number: { required: true, message: '请输入系列编号', trigger: 'blur' },
	card_series: { required: true, message: '请输入系列名称(中文)', trigger: 'blur' },
	abbr_series: { required: true, message: '请输入系列名称(英文)', trigger: 'blur' },
	card_code: { required: true, message: '请输入卡牌编号', trigger: 'blur' },
	card_cover: { required: true, message: '请选择卡片封面图', trigger: 'change' },
	card_img: { required: true, message: '请选择卡片背面图', trigger: 'change' },
}